Document: vdr-plugin-vdr-vdrmanager
Title: Debian vdr-plugin-vdr-vdrmanager Manual
Author: <insert document author here>
Abstract: This manual describes what vdr-plugin-vdr-vdrmanager is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vdr-plugin-vdr-vdrmanager/vdr-plugin-vdr-vdrmanager.sgml.gz

Format: postscript
Files: /usr/share/doc/vdr-plugin-vdr-vdrmanager/vdr-plugin-vdr-vdrmanager.ps.gz

Format: text
Files: /usr/share/doc/vdr-plugin-vdr-vdrmanager/vdr-plugin-vdr-vdrmanager.text.gz

Format: HTML
Index: /usr/share/doc/vdr-plugin-vdr-vdrmanager/html/index.html
Files: /usr/share/doc/vdr-plugin-vdr-vdrmanager/html/*.html
