/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_bjusystems_vdrmanager_utils_crypt_NativeDES */

#ifndef _Included_de_bjusystems_vdrmanager_utils_crypt_NativeDES
#define _Included_de_bjusystems_vdrmanager_utils_crypt_NativeDES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_bjusystems_vdrmanager_utils_crypt_NativeDES
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_bjusystems_vdrmanager_utils_crypt_NativeDES_encrypt
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     de_bjusystems_vdrmanager_utils_crypt_NativeDES
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_bjusystems_vdrmanager_utils_crypt_NativeDES_decrypt
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
